name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.9, 3.10, 3.11, 3.12]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry install --no-interaction --no-ansi

      - name: Run pre-commit
        run: |
          poetry run pre-commit run --all-files

      - name: Run tests with coverage
        run: |
          poetry run pytest -q --cov=src --cov-report=xml

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          files: coverage.xml
          fail_ci_if_error: true
# Below is a **surgical to-do list** you can tackle one file at a time.  I’ve ordered the fixes roughly by ROI: finish everything in **Step 0** first, then march down the file list.

# ---

# ## Step 0 – Repo-level hygiene (do once)

# | Action                                                                                                                                                                                                   | Why it matters                       |
# | -------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- | ------------------------------------ |
# | **Create `pyproject.toml`** with-in `[project]` dependencies (`numpy`, `pandas`, `numpy-financial`, `pydantic`, `typer`, `streamlit`, `plotly`, `markdown2`, `weasyprint`) and an editable `src` layout. | Removes “works-on-my-machine” smell. |
# | **Add `pre-commit`** (black, isort, flake8, mypy).                                                                                                                                                       | Static lint stops style drift.       |
# | **GitHub Actions**: matrix on 3.9 → 3.12 running `pytest -q`.                                                                                                                                            | Shows green badge to recruiters.     |
# | **Codecov badge** (>90 % lines)                                                                                                                                                                          | Signals test discipline.             |

# ---

# ## File-by-file fixes

# ### 1. `src/modules/lbo_model.py`

# | 🔧 Fix                                                                                                                           | Detail                                            |
# | -------------------------------------------------------------------------------------------------------------------------------- | ------------------------------------------------- |
# | **Parameterise hard-coded 70 / 30 split** of bullet vs amort debt; pass as kwargs with defaults.  Right now they’re literals .   | Makes model flexible for mezz / unitranche cases. |
# | **Move `amort_schedule = [amort_amt/5]*5` to a helper** and allow custom schedules.                                              | Models seven-year deals without code edits.       |
# | **Sweep hierarchy**: instead of paying only the first non-revolver tranche , iterate senior → subordinated until cash exhausted. | Reflects typical cash-waterfall.                  |
# | **Implement LTV covenant** (`enterprise_value * exit_multiple`) vs total debt each year; raise `CovenantBreachError` like ICR.   | Completes promised feature set.                   |
# | **Exit cash & WC unwind**: add cash balance build-up and working-capital release in exit IRR calc.                               | Removes rosy bias in IRR.                         |
# | **Docstrings & type hints** for every public method.                                                                             | Reviewer readability.                             |

# ### 2. `src/modules/fund_waterfall.py`

# | 🔧 Fix                                                                                                                                     | Detail |
# | ------------------------------------------------------------------------------------------------------------------------------------------ | ------ |
# | **Finish `reset_hurdle` logic** – after a tier is met, reduce base capital and recompute IRR; remove the stub comment .                    |        |
# | **True catch-up math**: calculate GP catch-up until GP gets X % of all distributed profit before moving to next tier.                      |        |
# | **Tier-by-tier carry** instead of “highest tier only”: loop through tiers and allocate incremental carry on the tranche above each hurdle. |        |
# | **Management-fee base**: make it choice of *committed* vs *drawn* capital; right now it’s always committed .                               |        |
# | **Annual fee offset**: subtract fees from distributions before hurdle tests; this is market practice.                                      |        |
# | **Clawback polish**: compare *net* GP carry (paid – taxes) to final entitlement; accrue interest on excess.                                |        |
# | **Return vs paid-in capital test**: ensure LP gets 100 % of paid-in + pref before any carry.                                               |        |

# ### 3. `src/modules/sensitivity.py`

# | 🔧 Fix                                                                               | Detail |
# | ------------------------------------------------------------------------------------ | ------ |
# | **Add confidence intervals** via bootstrap on IRR distribution.                      |        |
# | **Vectorise `run_2d_sensitivity`** with `itertools.product` + list-comp for speed.   |        |
# | **Optional heat-map export** (`plotly.express.imshow`).                              |        |
# | **Test coverage**: assert runtime < 1 s for a 100×100 grid to flag perf regressions. |        |

# ### 4. `cli.py`

# | 🔧 Fix                                                                                             | Detail |
# | -------------------------------------------------------------------------------------------------- | ------ |
# | **Typo in `Field(. gt=0)`** – the leading space breaks parsing; use `Field(gt=0, …)`               |        |
# | .                                                                                                  |        |
# | **`--years` global option** so users don’t edit JSON for horizon tweaks.                           |        |
# | **`typer.Option(Path(...), exists=True)`** is deprecated; switch to `FileText` or manual check.    |        |
# | **Surfacing error codes**: exit 2 for covenant breach, 3 for insolvency; CI can grep return codes. |        |

# ### 5. `streamlit_app.py`

# | 🔧 Fix                                                                                                                     | Detail |
# | -------------------------------------------------------------------------------------------------------------------------- | ------ |
# | **Sanitise user JSON** from `tiers_json` with `jsonschema.validate`; right now `eval()` risk is latent when you refactor . |        |
# | **Cache `convert_md_to_pdf`** with `@st.cache_data(ttl=3600)` to avoid heavy WeasyPrint re-runs.                           |        |
# | **Guard against large uploads** – max file size sidebar setting.                                                           |        |
# | **Accessibility**: add alt-text for Plotly traces via `hovertext`.                                                         |        |

# ### 6. `cashflow.py`

# | 🔧 Fix                                                                                | Detail |
# | ------------------------------------------------------------------------------------- | ------ |
# | **Remove duplicate logic with `lbo_model`** – keep in one place, import in the other. |        |
# | **Return `pd.DataFrame` directly** instead of dict-of-dicts for usability.            |        |

# ### 7. `exit.py`

# | 🔧 Fix                                                                                        | Detail |
# | --------------------------------------------------------------------------------------------- | ------ |
# | **Use `numpy_financial.irr`** instead of custom CAGR when cash flows aren’t annual lump sums. |        |
# | **Handle negative equity value** by returning `None` IRR, not −1 sentinel .                   |        |
# | **Add option for sale costs (%) and leverage recap**.                                         |        |

# ### 8. Tests (`tests/*.py`)

# | 🔧 Fix                                                                                           | Detail |
# | ------------------------------------------------------------------------------------------------ | ------ |
# | **Parametrise** pytest cases with `@pytest.mark.parametrize` instead of copy-paste blocks.       |        |
# | **Add property-based tests** (`hypothesis`) to fuzz weird tiers, fee rates, and amort schedules. |        |
# | **Contract tests vs Excel**: load a simple spreadsheet waterfall, assert parity.                 |        |

# ---

# ## Suggested implementation sequence

# 1. **Fund waterfall core fixes** (carry tiers, reset hurdle).
# 2. **LBO model debt & covenant realism**.
# 3. **Repo packaging + CI** (do once features stabilise).
# 4. **Streamlit security & performance tweaks**.
# 5. **Sensitivity visual extras & hypothesis tests**.

# Finishing items 1-3 gets you to the “minimum publishable model”; items 4-8 are polish that will impress reviewers but aren’t blocking the paper.
